### ISSUE TITLE
Is there any information for IoT core registry access for CPU utilisation and RAM memory counter

### ISSUE THREAD

**Issue by pratson20** [MicrosoftDocs/windows-iotcore-docs#1518]
Hi,

I am trying to access CPU utilisation and RAM memory counter but seeing issue on Win IoT Core OS. Same code is working fine on Windows Enterprise.

Below is the issue which i am facing-
`Unhandled Exception: System.AggregateException: One or more errors occurred. (Access to the registry key 'Global' is denied.) ---> System.UnauthorizedAccessException: Access to the registry key 'Global' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.InternalGetValueCore(String name, Object defaultValue, Boolean doNotExpand)
   at System.Diagnostics.PerformanceMonitor.GetData(String item)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(String item)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at memorymetricsmodule.Program.InitialiseCPUCounter() in C:\app\Program.cs:line 69
   at memorymetricsmodule.Program.Init() in C:\app\Program.cs:line 61
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at memorymetricsmodule.Program.Main(String[] args) in C:\app\Program.cs:line 31`

Code Snippet-
`
        private static void InitialiseCPUCounter()
        {
            cpuCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total", true);
        }
`
```
        private static void InitializeRAMCounter()
        {
            ramCounter = new PerformanceCounter("Processor", "% Processor Time", "_Total");
        }
```

Could you please let me know how can i solve this issue.

Thanks

**Comment by saraclay** [comment]
Please post this on [our forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=WindowsIoT). Our GitHub issues are for documentation related inquiries only. Thank you.
